version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - node.roles=master,data,ingest
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g #change this to 50% memory of your system
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD="akdjhf@hdJ9uvdjsvvjvsvhUI&G36789"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - /mnt/data:/usr/share/opensearch/data
      - /root/datastore-eval/opensearch/anonymous-auth-config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - /root/datastore-eval/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
#  kibana:
#    image: docker.elastic.co/kibana/kibana:9.1.0
#    environment:
#      - ELASTICSEARCH_HOSTS=http://opensearch:9200
#    ports:
#      - "5601:5601"
#    depends_on:
#      - opensearch
