services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.5.3.5
    ports:
      - "9000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ${PWD}/config.d:/etc/clickhouse-server/config.d:ro
      - ${PWD}/users.d:/etc/clickhouse-server/users.d:rw
      - ${PWD}/certs:/etc/clickhouse-server/certs:ro
      - ${PWD}/dictionaries:/var/lib/clickhouse/user_files/dictionaries:rw
      - ./data/clickhouse/:/var/lib/clickhouse    
    restart: unless-stopped